### PR TITLE
Fix incorrect implicit integer-pointer conversions

### LINKED ISSUE #10: Bug: Commit hook always fails
With 97f2e2cd346c661b0fc4895d007136fb5e3151c5 I always get the following screen, when I try to commit:

commit hook failed

I do not have any commit hooks configured. With a previous version a890f7e2cd13b36a0301c44022808685bd43a3c9 all is good and the screen is not shown.

### PR DESCRIPTION
**Pull request by nanotech**
In particular, fixing [`return @"";`](https://github.com/ssp/gitx/compare/ssp:7715867...nanotech:c594e7d#diff-ea6d3badb7e586744f89b10a23f7dc2cL1129) fixed #10 for me. Perhaps it depends on where the compiler places the `__NSCFConstantString` for `@""` in the executable?

### CODE REVIEW

File: Classes/Controllers/PBRepositoryDocumentController.m [hunk 1]
```diff
@@ -42,8 +42,8 @@ - (id)makeUntitledDocumentOfType:(NSString *)typeName error:(NSError *__autorele
         return nil;
     }
 
-	BOOL success = [GTRepository initializeEmptyRepositoryAtFileURL:[op URL] options:nil error:outError];
-    if (!success)
+	GTRepository *repo = [GTRepository initializeEmptyRepositoryAtFileURL:[op URL] options:nil error:outError];
+    if (!repo)
```
Comment (ssp) [inline Classes/Controllers/PBRepositoryDocumentController.m]: whoops … good Find!

When we're having a pointer here, would a != nil check look more »correct« than treating the variable as boolean?

Comment (nanotech) [inline Classes/Controllers/PBRepositoryDocumentController.m]: `if (!ptr)` is quite idiomatic and common in C family languages in my experience. Swift does require `!= nil` however, as do other languages with fewer or no implicit conversions.
